In [1]:
# --- IMPORTS ---
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import mannwhitneyu
from scipy.stats import shapiro
from scipy import stats
import math
from matplotlib.ticker import MaxNLocator

# Show all rows and all columns
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)

# Show full contents of each cell (no truncation)
pd.set_option("display.max_colwidth", None)

# Make the dataframe print across the full console width
pd.set_option("display.width", 0)

In [2]:
# NORMALISATION CHECKS

df = pd.read_csv('../data/Jacob Spectrum Report for 20240628_Rats_no_header.csv')

In [3]:
df = df.rename(columns = {'Variable modifications identified by spectrum' : 'pep_mods'})
df = df.rename(columns = {'Peptide start index' : 'pep_start'})
df = df.rename(columns = {'Peptide stop index' : 'pep_end'})
df = df.rename(columns = {'MS/MS sample name' : 'sample'})
df["pep_mods"] = df["pep_mods"].str.replace(r"Oxidation|Deamidated", "", regex=True)

In [4]:
# lds = list of datasets []
# m = specific modification 'oxP'
# l = loci range ( , )

def findtotalptms(lds, p, *args, **kwargs):    
    PTMdf = pd.DataFrame(columns = ['Sample', 'Prot', '50aa_reg_start', '50aa_reg_end', '50aa_reg_range', 'oxP', 'oxM', 'oxK', 'dNQ', 'SurrOxP', 'SurrOxM', 'SurrOxK', 'SurrDNQ'])
    for ds in lds:  
        ldslabels = ds['sample'].unique()
        print('ldslabels', ldslabels)
        ds["pep_mods"] = ds["pep_mods"].fillna("")
        ds["pep_mods"] = ds["pep_mods"].astype(str)
        for d in ldslabels:
            dataset = ds[ds['sample'] == d]
            prots = dataset['Alternate IDs'].unique()
            for prot in p:
                data = dataset[dataset['Alternate IDs'] == prot]
                maxaapos = data['pep_end'].max()
                max50aagap = math.ceil(maxaapos / 50) * 50
                increments = [(i, i + 50) for i in range(0, max50aagap, 50)]
                for r in increments:
                    datasubset = data[(data['pep_start'].between(r[0],r[1])) | (data['pep_end'].between(r[0],r[1]))]
                    surrdata = data[data['pep_start'].between(r[0] - 50,r[1] + 50) | data['pep_end'].between(r[0] - 50,r[1] + 50)]  
                    oxP = datasubset['pep_mods'].str.count('p').sum()
                    oxK = datasubset['pep_mods'].str.count('k').sum()
                    oxM = datasubset['pep_mods'].str.count('m').sum()
                    dNQ = (datasubset['pep_mods'].str.count('n').sum()) + (datasubset['pep_mods'].str.count('q').sum())

                    oxPsurr = surrdata['pep_mods'].str.count('p').sum()
                    oxKsurr = surrdata['pep_mods'].str.count('k').sum()
                    oxMsurr = surrdata['pep_mods'].str.count('m').sum()
                    dNQsurr = (surrdata['pep_mods'].str.count('n').sum()) + (surrdata['pep_mods'].str.count('q').sum())

                    PTMdf.loc[len(PTMdf)] = [data['sample'].iloc[0], prot, r[0], r[1], f'{r[0]} - {r[1]}', oxP, oxM, oxK, dNQ, oxPsurr, oxMsurr, oxKsurr, dNQsurr]

    return PTMdf

In [10]:
femproteinList = ['Apoe', 'Col1a1', 'Col1a2', 'Col2a1', 'Comp', 'Spp1', 'Serpinh1', 'F2']
maleproteinList = ['Apoe', 'Col1a1', 'Col1a2', 'Col2a1', 'Comp', 'Spp1', 'Serpinh1', 'F2']

juvquantmods = findtotalptms([juvdf], femproteinList)
adultquantmods = findtotalptms([adultdf], maleproteinList)

ldslabels ['FZ1_F (ms-status_RAT1)' 'FZ2_F (ms-status_RAT2)'
 'FZ3_F (ms-status_RAT3)' 'FZ4_M (ms-status_RAT4)'
 'FZ5_M (ms-status_RAT5)' 'FZ6_M (ms-status_RAT6)']

C:\Users\jtudo\AppData\Local\Temp\ipykernel_23936\3987044331.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ds["pep_mods"] = ds["pep_mods"].fillna("")
C:\Users\jtudo\AppData\Local\Temp\ipykernel_23936\3987044331.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ds["pep_mods"] = ds["pep_mods"].astype(str)

ldslabels ['JA1_M (ms-status_RAT7)' 'JA2_F (ms-status_RAT8)'
 'JA3_M (ms-status_RAT9)' 'JA4_M (ms-status_RAT10)'
 'JA5_F (ms-status_RAT11)' 'JA6_F (ms-status_RAT12)']

C:\Users\jtudo\AppData\Local\Temp\ipykernel_23936\3987044331.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ds["pep_mods"] = ds["pep_mods"].fillna("")
C:\Users\jtudo\AppData\Local\Temp\ipykernel_23936\3987044331.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ds["pep_mods"] = ds["pep_mods"].astype(str)

In [11]:
proteinList = ['Apoe', 'Col1a1', 'Col1a2', 'Col2a1', 'Comp', 'Spp1', 'Serpinh1', 'F2']

MaleData = pd.concat([juvdf_m, adultdf_m])


malequantmods = findtotalptms([juvdf], proteinList)
femalequantmods = findtotalptms([adultdf], proteinList)

ldslabels ['FZ1_F (ms-status_RAT1)' 'FZ2_F (ms-status_RAT2)'
 'FZ3_F (ms-status_RAT3)' 'FZ4_M (ms-status_RAT4)'
 'FZ5_M (ms-status_RAT5)' 'FZ6_M (ms-status_RAT6)']

C:\Users\jtudo\AppData\Local\Temp\ipykernel_23936\3987044331.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ds["pep_mods"] = ds["pep_mods"].fillna("")
C:\Users\jtudo\AppData\Local\Temp\ipykernel_23936\3987044331.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ds["pep_mods"] = ds["pep_mods"].astype(str)

ldslabels ['JA1_M (ms-status_RAT7)' 'JA2_F (ms-status_RAT8)'
 'JA3_M (ms-status_RAT9)' 'JA4_M (ms-status_RAT10)'
 'JA5_F (ms-status_RAT11)' 'JA6_F (ms-status_RAT12)']

C:\Users\jtudo\AppData\Local\Temp\ipykernel_23936\3987044331.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ds["pep_mods"] = ds["pep_mods"].fillna("")
C:\Users\jtudo\AppData\Local\Temp\ipykernel_23936\3987044331.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ds["pep_mods"] = ds["pep_mods"].astype(str)

In [12]:
adultmale = findtotalptms([adultdf_m], proteinList)
juvmale = findtotalptms([juvdf_m], proteinList)

adultfemale = findtotalptms([adultdf_f], proteinList)
juvfemale = findtotalptms([juvdf_f], proteinList)

ldslabels ['JA1_M (ms-status_RAT7)' 'JA3_M (ms-status_RAT9)'
 'JA4_M (ms-status_RAT10)']

C:\Users\jtudo\AppData\Local\Temp\ipykernel_23936\3987044331.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ds["pep_mods"] = ds["pep_mods"].fillna("")
C:\Users\jtudo\AppData\Local\Temp\ipykernel_23936\3987044331.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ds["pep_mods"] = ds["pep_mods"].astype(str)

ldslabels ['FZ3_F (ms-status_RAT3)' 'FZ4_M (ms-status_RAT4)'
 'FZ5_M (ms-status_RAT5)']

C:\Users\jtudo\AppData\Local\Temp\ipykernel_23936\3987044331.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ds["pep_mods"] = ds["pep_mods"].fillna("")
C:\Users\jtudo\AppData\Local\Temp\ipykernel_23936\3987044331.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ds["pep_mods"] = ds["pep_mods"].astype(str)

ldslabels ['JA2_F (ms-status_RAT8)' 'JA5_F (ms-status_RAT11)'
 'JA6_F (ms-status_RAT12)']

C:\Users\jtudo\AppData\Local\Temp\ipykernel_23936\3987044331.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ds["pep_mods"] = ds["pep_mods"].fillna("")
C:\Users\jtudo\AppData\Local\Temp\ipykernel_23936\3987044331.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ds["pep_mods"] = ds["pep_mods"].astype(str)

ldslabels ['FZ1_F (ms-status_RAT1)' 'FZ2_F (ms-status_RAT2)'
 'FZ6_M (ms-status_RAT6)']

C:\Users\jtudo\AppData\Local\Temp\ipykernel_23936\3987044331.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ds["pep_mods"] = ds["pep_mods"].fillna("")
C:\Users\jtudo\AppData\Local\Temp\ipykernel_23936\3987044331.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ds["pep_mods"] = ds["pep_mods"].astype(str)

In [13]:
def pivotmods(data):
    d = data
    d = d.pivot_table(
        index=["Prot","50aa_reg_range"],      # rows
        columns="Sample",                     # columns by sample
        values=["oxP","oxM","oxK","dNQ"],     # values
        fill_value=0                           # fill missing counts with 0
    )
    # d.drop(['SurrOxP', 'SurrOxM', 'SurrOxK', 'SurrDNQ'])

    # Optional: flatten multi-level columns
    d.columns = [f"{mod}_{sample}" for mod, sample in d.columns]
    d.reset_index(inplace=True)

    return d

In [14]:
malejuvmodspiv = pivotmods(juvmale)
maleadultmodspiv = pivotmods(adultmale)

femalejuvmodspiv = pivotmods(juvfemale)
femaleadultmodspiv = pivotmods(adultfemale)

In [15]:
femaleadultmodspiv.columns

Index(['Prot', '50aa_reg_range', 'dNQ_JA2_F (ms-status_RAT8)',
       'dNQ_JA5_F (ms-status_RAT11)', 'dNQ_JA6_F (ms-status_RAT12)',
       'oxK_JA2_F (ms-status_RAT8)', 'oxK_JA5_F (ms-status_RAT11)',
       'oxK_JA6_F (ms-status_RAT12)', 'oxM_JA2_F (ms-status_RAT8)',
       'oxM_JA5_F (ms-status_RAT11)', 'oxM_JA6_F (ms-status_RAT12)',
       'oxP_JA2_F (ms-status_RAT8)', 'oxP_JA5_F (ms-status_RAT11)',
       'oxP_JA6_F (ms-status_RAT12)'],
      dtype='object')

In [16]:
dNQCols = ['dNQ_JA2_F (ms-status_RAT8)', 'dNQ_JA5_F (ms-status_RAT11)', 'dNQ_JA6_F (ms-status_RAT12)']
oxKCols = ['oxK_JA2_F (ms-status_RAT8)', 'oxK_JA5_F (ms-status_RAT11)', 'oxK_JA6_F (ms-status_RAT12)']
oxMCols = ['oxM_JA2_F (ms-status_RAT8)', 'oxM_JA5_F (ms-status_RAT11)', 'oxM_JA6_F (ms-status_RAT12)']
oxPCols = ['oxP_JA2_F (ms-status_RAT8)', 'oxP_JA5_F (ms-status_RAT11)', 'oxP_JA6_F (ms-status_RAT12)']

for group, cols in {
    'AVG. dNQ': dNQCols,
    'AVG. oxK': oxKCols,
    'AVG. oxM': oxMCols,
    'AVG. oxP': oxPCols
}.items():
    femaleadultmodspiv[f'{group}_median'] = femaleadultmodspiv[cols].median(axis=1)

femaleadultmodspiv.head()

,Prot,50aa_reg_range,dNQ_JA2_F (ms-status_RAT8),dNQ_JA5_F (ms-status_RAT11),dNQ_JA6_F (ms-status_RAT12),oxK_JA2_F (ms-status_RAT8),oxK_JA5_F (ms-status_RAT11),oxK_JA6_F (ms-status_RAT12),oxM_JA2_F (ms-status_RAT8),oxM_JA5_F (ms-status_RAT11),oxM_JA6_F (ms-status_RAT12),oxP_JA2_F (ms-status_RAT8),oxP_JA5_F (ms-status_RAT11),oxP_JA6_F (ms-status_RAT12),AVG. dNQ_median,AVG. oxK_median,AVG. oxM_median,AVG. oxP_median
0,Apoe,0 - 50,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0
1,Apoe,100 - 150,2,5,2,0,0,0,4,6,5,0,0,0,2.0,0.0,5.0,0.0
2,Apoe,150 - 200,0,1,1,0,0,0,0,0,0,0,0,0,1.0,0.0,0.0,0.0
3,Apoe,200 - 250,1,2,0,0,0,0,0,0,0,0,0,0,1.0,0.0,0.0,0.0
4,Apoe,250 - 300,2,3,1,2,2,2,3,7,6,2,2,2,2.0,2.0,6.0,2.0

In [17]:
dNQCols = ['dNQ_FZ1_F (ms-status_RAT1)', 'dNQ_FZ2_F (ms-status_RAT2)', 'dNQ_FZ6_M (ms-status_RAT6)']
oxKCols = ['oxK_FZ1_F (ms-status_RAT1)', 'oxK_FZ2_F (ms-status_RAT2)', 'oxK_FZ6_M (ms-status_RAT6)']
oxMCols = ['oxM_FZ1_F (ms-status_RAT1)', 'oxM_FZ2_F (ms-status_RAT2)', 'oxM_FZ6_M (ms-status_RAT6)']
oxPCols = ['oxP_FZ1_F (ms-status_RAT1)', 'oxP_FZ2_F (ms-status_RAT2)', 'oxP_FZ6_M (ms-status_RAT6)']

for group, cols in {
    'AVG. dNQ': dNQCols,
    'AVG. oxK': oxKCols,
    'AVG. oxM': oxMCols,
    'AVG. oxP': oxPCols
}.items():
    femalejuvmodspiv[f'{group}_median'] = femalejuvmodspiv[cols].median(axis=1)

femalejuvmodspiv.head()

,Prot,50aa_reg_range,dNQ_FZ1_F (ms-status_RAT1),dNQ_FZ2_F (ms-status_RAT2),dNQ_FZ6_M (ms-status_RAT6),oxK_FZ1_F (ms-status_RAT1),oxK_FZ2_F (ms-status_RAT2),oxK_FZ6_M (ms-status_RAT6),oxM_FZ1_F (ms-status_RAT1),oxM_FZ2_F (ms-status_RAT2),oxM_FZ6_M (ms-status_RAT6),oxP_FZ1_F (ms-status_RAT1),oxP_FZ2_F (ms-status_RAT2),oxP_FZ6_M (ms-status_RAT6),AVG. dNQ_median,AVG. oxK_median,AVG. oxM_median,AVG. oxP_median
0,Apoe,0 - 50,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0
1,Apoe,100 - 150,0,2,1,0,0,0,3,6,5,0,0,0,1.0,0.0,5.0,0.0
2,Apoe,150 - 200,0,1,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0
3,Apoe,200 - 250,0,3,2,0,0,0,0,0,0,0,0,0,2.0,0.0,0.0,0.0
4,Apoe,250 - 300,0,2,1,0,0,0,1,4,3,0,0,0,1.0,0.0,3.0,0.0

In [18]:
dNQCols = ['dNQ_FZ3_F (ms-status_RAT3)', 'dNQ_FZ4_M (ms-status_RAT4)', 'dNQ_FZ5_M (ms-status_RAT5)']
oxKCols = ['oxK_FZ3_F (ms-status_RAT3)', 'oxK_FZ4_M (ms-status_RAT4)', 'oxK_FZ5_M (ms-status_RAT5)']
oxMCols = ['oxM_FZ3_F (ms-status_RAT3)', 'oxM_FZ5_M (ms-status_RAT5)', 'oxM_FZ5_M (ms-status_RAT5)']
oxPCols = ['oxP_FZ3_F (ms-status_RAT3)', 'oxP_FZ4_M (ms-status_RAT4)', 'oxP_FZ5_M (ms-status_RAT5)']

for group, cols in {
    'AVG. dNQ': dNQCols,
    'AVG. oxK': oxKCols,
    'AVG. oxM': oxMCols,
    'AVG. oxP': oxPCols
}.items():
    malejuvmodspiv[f'{group}_median'] = malejuvmodspiv[cols].median(axis=1)

malejuvmodspiv.head()

,Prot,50aa_reg_range,dNQ_FZ3_F (ms-status_RAT3),dNQ_FZ4_M (ms-status_RAT4),dNQ_FZ5_M (ms-status_RAT5),oxK_FZ3_F (ms-status_RAT3),oxK_FZ4_M (ms-status_RAT4),oxK_FZ5_M (ms-status_RAT5),oxM_FZ3_F (ms-status_RAT3),oxM_FZ4_M (ms-status_RAT4),oxM_FZ5_M (ms-status_RAT5),oxP_FZ3_F (ms-status_RAT3),oxP_FZ4_M (ms-status_RAT4),oxP_FZ5_M (ms-status_RAT5),AVG. dNQ_median,AVG. oxK_median,AVG. oxM_median,AVG. oxP_median
0,Apoe,0 - 50,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0
1,Apoe,100 - 150,0,1,0,0,0,0,2,4,2,0,0,0,0.0,0.0,2.0,0.0
2,Apoe,150 - 200,1,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0
3,Apoe,200 - 250,0,2,2,0,0,0,0,0,0,0,0,0,2.0,0.0,0.0,0.0
4,Apoe,250 - 300,0,0,1,0,0,0,2,2,1,0,0,0,0.0,0.0,1.0,0.0

In [19]:
dNQCols = ['dNQ_JA1_M (ms-status_RAT7)', 'dNQ_JA3_M (ms-status_RAT9)', 'dNQ_JA4_M (ms-status_RAT10)']
oxKCols = ['oxK_JA1_M (ms-status_RAT7)', 'oxK_JA3_M (ms-status_RAT9)', 'oxK_JA4_M (ms-status_RAT10)']
oxMCols = ['oxM_JA1_M (ms-status_RAT7)', 'oxM_JA3_M (ms-status_RAT9)', 'oxM_JA4_M (ms-status_RAT10)']
oxPCols = ['oxP_JA1_M (ms-status_RAT7)', 'oxP_JA3_M (ms-status_RAT9)', 'oxP_JA4_M (ms-status_RAT10)']

for group, cols in {
    'AVG. dNQ': dNQCols,
    'AVG. oxK': oxKCols,
    'AVG. oxM': oxMCols,
    'AVG. oxP': oxPCols
}.items():
    maleadultmodspiv[f'{group}_median'] = maleadultmodspiv[cols].median(axis=1)

maleadultmodspiv.head()

,Prot,50aa_reg_range,dNQ_JA1_M (ms-status_RAT7),dNQ_JA3_M (ms-status_RAT9),dNQ_JA4_M (ms-status_RAT10),oxK_JA1_M (ms-status_RAT7),oxK_JA3_M (ms-status_RAT9),oxK_JA4_M (ms-status_RAT10),oxM_JA1_M (ms-status_RAT7),oxM_JA3_M (ms-status_RAT9),oxM_JA4_M (ms-status_RAT10),oxP_JA1_M (ms-status_RAT7),oxP_JA3_M (ms-status_RAT9),oxP_JA4_M (ms-status_RAT10),AVG. dNQ_median,AVG. oxK_median,AVG. oxM_median,AVG. oxP_median
0,Apoe,0 - 50,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0
1,Apoe,100 - 150,2,2,5,0,0,0,3,4,6,0,0,0,2.0,0.0,4.0,0.0
2,Apoe,150 - 200,1,0,1,0,0,0,0,0,0,0,0,0,1.0,0.0,0.0,0.0
3,Apoe,200 - 250,1,1,2,0,0,0,0,0,0,0,0,0,1.0,0.0,0.0,0.0
4,Apoe,250 - 300,3,2,3,2,2,2,4,3,7,2,2,2,3.0,2.0,4.0,2.0

In [50]:
maleadultmodspiv

,Prot,50aa_reg_range,dNQ_JA1_M (ms-status_RAT7),dNQ_JA3_M (ms-status_RAT9),dNQ_JA4_M (ms-status_RAT10),oxK_JA1_M (ms-status_RAT7),oxK_JA3_M (ms-status_RAT9),oxK_JA4_M (ms-status_RAT10),oxM_JA1_M (ms-status_RAT7),oxM_JA3_M (ms-status_RAT9),oxM_JA4_M (ms-status_RAT10),oxP_JA1_M (ms-status_RAT7),oxP_JA3_M (ms-status_RAT9),oxP_JA4_M (ms-status_RAT10),AVG. dNQ_median,AVG. oxK_median,AVG. oxM_median,AVG. oxP_median
0,Apoe,0 - 50,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0
1,Apoe,100 - 150,2,2,5,0,0,0,3,4,6,0,0,0,2.0,0.0,4.0,0.0
2,Apoe,150 - 200,1,0,1,0,0,0,0,0,0,0,0,0,1.0,0.0,0.0,0.0
3,Apoe,200 - 250,1,1,2,0,0,0,0,0,0,0,0,0,1.0,0.0,0.0,0.0
4,Apoe,250 - 300,3,2,3,2,2,2,4,3,7,2,2,2,3.0,2.0,4.0,2.0
5,Apoe,50 - 100,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0
6,Col1a1,0 - 50,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0
7,Col1a1,100 - 150,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0
8,Col1a1,1000 - 1050,0,0,1,1,4,3,15,18,16,70,103,90,0.0,3.0,16.0,90.0
9,Col1a1,1050 - 1100,3,2,3,1,1,0,0,0,0,23,39,32,3.0,1.0,0.0,32.0
10,Col1a1,1100 - 1150,5,8,7,1,2,2,0,0,0,79,89,75,7.0,2.0,0.0,79.0
11,Col1a1,1150 - 1200,2,2,4,1,2,2,0,0,0,45,47,48,2.0,2.0,0.0,47.0
12,Col1a1,1200 - 1250,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0
13,Col1a1,1250 - 1300,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0
14,Col1a1,1300 - 1350,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0
15,Col1a1,1350 - 1400,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0
16,Col1a1,1400 - 1450,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0
17,Col1a1,150 - 200,0,0,0,0,0,0,5,5,5,10,16,14,0.0,0.0,5.0,14.0
18,Col1a1,200 - 250,2,0,0,3,5,5,6,8,9,24,55,29,0.0,5.0,8.0,29.0
19,Col1a1,250 - 300,3,0,3,8,9,12,11,8,14,41,50,58,3.0,9.0,11.0,50.0
20,Col1a1,300 - 350,5,3,4,5,5,3,0,0,0,40,47,50,4.0,5.0,0.0,47.0
21,Col1a1,350 - 400,8,11,11,6,8,6,0,0,0,67,109,69,11.0,6.0,0.0,69.0
22,Col1a1,400 - 450,4,5,5,6,3,4,0,0,0,41,47,42,5.0,4.0,0.0,42.0
23,Col1a1,450 - 500,1,1,1,4,5,3,0,0,0,57,51,53,1.0,4.0,0.0,53.0
24,Col1a1,50 - 100,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0
25,Col1a1,500 - 550,0,1,1,4,5,6,0,0,0,34,36,37,1.0,5.0,0.0,36.0
26,Col1a1,550 - 600,4,6,7,16,22,21,7,9,12,34,47,48,6.0,21.0,9.0,47.0
27,Col1a1,600 - 650,1,2,0,0,1,0,0,0,0,14,16,15,1.0,0.0,0.0,15.0
28,Col1a1,650 - 700,6,7,4,7,6,5,7,6,4,63,66,39,6.0,6.0,6.0,63.0
29,Col1a1,700 - 750,5,6,2,8,7,7,7,6,4,63,64,37,5.0,7.0,6.0,63.0
30,Col1a1,750 - 800,0,1,0,18,15,7,0,0,0,62,69,49,0.0,15.0,0.0,62.0
31,Col1a1,800 - 850,1,1,1,14,14,13,0,0,0,54,73,55,1.0,14.0,0.0,55.0
32,Col1a1,850 - 900,3,2,3,16,16,20,0,0,0,72,77,70,3.0,16.0,0.0,72.0
33,Col1a1,900 - 950,1,1,1,2,3,3,0,0,0,11,23,18,1.0,3.0,0.0,18.0
34,Col1a1,950 - 1000,1,2,2,0,0,0,15,18,16,86,86,83,2.0,0.0,16.0,86.0
35,Col1a2,0 - 50,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0
36,Col1a2,100 - 150,0,1,0,2,0,0,2,3,5,9,11,6,0.0,0.0,3.0,9.0
37,Col1a2,1000 - 1050,17,10,23,8,11,11,0,0,0,48,48,56,17.0,11.0,0.0,48.0
38,Col1a2,1050 - 1100,15,9,19,8,11,11,0,0,0,41,44,49,15.0,11.0,0.0,44.0
39,Col1a2,1100 - 1150,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0
40,Col1a2,1150 - 1200,0,0,0,0,0,0,1,1,0,0,0,0,0.0,0.0,1.0,0.0
41,Col1a2,1200 - 1250,1,1,0,0,0,0,0,0,0,0,0,0,1.0,0.0,0.0,0.0
42,Col1a2,1250 - 1300,1,1,0,0,0,0,1,4,2,0,0,0,1.0,0.0,2.0,0.0
43,Col1a2,1300 - 1350,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0
44,Col1a2,1350 - 1400,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0
45,Col1a2,150 - 200,0,1,1,9,4,7,0,0,0,22,20,25,1.0,7.0,0.0,22.0
46,Col1a2,200 - 250,0,0,0,3,1,2,0,0,0,8,38,42,0.0,2.0,0.0,38.0
47,Col1a2,250 - 300,0,0,0,2,4,5,0,0,0,9,12,23,0.0,4.0,0.0,12.0
48,Col1a2,300 - 350,0,0,0,1,5,5,0,0,0,17,27,21,0.0,5.0,0.0,21.0
49,Col1a2,350 - 400,0,0,0,0,2,2,0,0,0,20,35,31,0.0,2.0,0.0,31.0
50,Col1a2,400 - 450,0,0,0,0,0,0,2,12,11,25,48,44,0.0,0.0,11.0,44.0
51,Col1a2,450 - 500,1,1,1,3,4,3,1,2,2,25,32,32,1.0,3.0,2.0,32.0
52,Col1a2,50 - 100,0,0,0,0,0,0,2,3,5,2,1,2,0.0,0.0,3.0,2.0
53,Col1a2,500 - 550,1,1,1,9,18,8,0,0,0,21,30,20,1.0,9.0,0.0,21.0
54,Col1a2,550 - 600,0,0,0,2,2,2,0,0,0,16,15,18,0.0,2.0,0.0,16.0
55,Col1a2,600 - 650,2,2,3,7,6,5,0,0,0,32,22,22,2.0,6.0,0.0,22.0
56,Col1a2,650 - 700,2,2,3,8,6,5,0,0,0,42,38,31,2.0,6.0,0.0,38.0
57,Col1a2,700 - 750,0,0,1,6,6,5,0,0,0,10,13,9,0.0,6.0,0.0,10.0
58,Col1a2,750 - 800,0,1,0,1,1,1,3,3,1,16,17,14,0.0,1.0,3.0,16.0
59,Col1a2,800 - 850,0,0,1,0,2,3,3,3,1,33,40,45,0.0,2.0,3.0,40.0
60,Col1a2,850 - 900,0,0,0,0,1,1,0,0,0,6,6,7,0.0,1.0,0.0,6.0
61,Col1a2,900 - 950,0,2,3,0,0,0,0,0,0,7,30,24,2.0,0.0,0.0,24.0
62,Col1a2,950 - 1000,4,2,4,0,0,0,0,0,0,23,10,18,4.0,0.0,0.0,18.0
63,Col2a1,0 - 50,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0
64,Col2a1,100 - 150,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0
65,Col2a1,1000 - 1050,0,0,0,0,0,1,1,1,2,0,4,4,0.0,0.0,1.0,4.0
66,Col2a1,1050 - 1100,0,0,0,0,0,0,0,0,0,5,6,5,0.0,0.0,0.0,5.0
67,Col2a1,1100 - 1150,0,0,0,0,0,0,0,0,0,8,4,0,0.0,0.0,0.0,4.0
68,Col2a1,1150 - 1200,4,5,5,1,0,2,0,0,2,5,0,0,5.0,1.0,0.0,0.0
69,Col2a1,1200 - 1250,6,8,7,1,0,0,2,3,1,0,0,0,7.0,0.0,2.0,0.0
70,Col2a1,1250 - 1300,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0
71,Col2a1,1300 - 1350,9,5,9,0,0,0,5,5,6,0,0,0,9.0,0.0,5.0,0.0
72,Col2a1,1350 - 1400,7,5,6,0,0,0,5,5,6,0,0,0,6.0,0.0,5.0,0.0
73,Col2a1,150 - 200,0,0,0,0,0,0,0,0,0,3,0,0,0.0,0.0,0.0,0.0
74,Col2a1,200 - 250,0,0,0,1,0,2,0,0,0,3,0,6,0.0,1.0,0.0,3.0
75,Col2a1,250 - 300,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0
76,Col2a1,300 - 350,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0
77,Col2a1,350 - 400,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0
78,Col2a1,400 - 450,0,0,0,0,0,0,0,0,0,4,5,7,0.0,0.0,0.0,5.0
79,Col2a1,450 - 500,0,0,0,0,0,0,0,0,0,1,5,4,0.0,0.0,0.0,4.0
80,Col2a1,50 - 100,0,0,0,0,0,0,0,0,0,0,1,1,0.0,0.0,0.0,1.0
81,Col2a1,500 - 550,0,0,1,0,0,0,0,0,0,4,4,12,0.0,0.0,0.0,4.0
82,Col2a1,550 - 600,0,0,0,0,0,0,0,0,0,2,2,3,0.0,0.0,0.0,2.0
83,Col2a1,600 - 650,0,0,1,0,0,0,0,0,0,2,0,2,0.0,0.0,0.0,2.0
84,Col2a1,650 - 700,0,0,1,0,0,0,0,0,0,1,0,2,0.0,0.0,0.0,1.0
85,Col2a1,700 - 750,0,0,0,0,0,0,0,0,0,0,0,3,0.0,0.0,0.0,0.0
86,Col2a1,750 - 800,0,0,0,0,0,0,0,0,0,0,0,3,0.0,0.0,0.0,0.0
87,Col2a1,800 - 850,1,0,1,0,1,3,0,0,0,6,9,10,1.0,1.0,0.0,9.0
88,Col2a1,850 - 900,0,0,0,0,1,3,0,0,0,0,5,8,0.0,1.0,0.0,5.0
89,Col2a1,900 - 950,0,0,1,0,0,0,0,0,0,27,29,21,0.0,0.0,0.0,27.0
90,Col2a1,950 - 1000,0,0,0,0,0,1,0,0,0,0,8,3,0.0,0.0,0.0,3.0
91,Comp,0 - 50,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0
92,Comp,100 - 150,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0
93,Comp,150 - 200,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0
94,Comp,200 - 250,0,1,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0
95,Comp,250 - 300,0,1,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0
96,Comp,300 - 350,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0
97,Comp,350 - 400,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0
98,Comp,400 - 450,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0
99,Comp,450 - 500,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0
100,Comp,50 - 100,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0
101,Comp,500 - 550,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0
102,Comp,550 - 600,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0
103,Comp,600 - 650,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0
104,Comp,650 - 700,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0
105,F2,0 - 50,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0
106,F2,100 - 150,0,0,0,0,0,0,1,2,2,0,0,0,0.0,0.0,2.0,0.0
107,F2,150 - 200,0,0,1,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0
108,F2,200 - 250,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0
109,F2,250 - 300,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0
110,F2,300 - 350,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0
111,F2,350 - 400,0,0,0,0,0,0,0,0,1,0,0,0,0.0,0.0,0.0,0.0
112,F2,400 - 450,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0
113,F2,450 - 500,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0
114,F2,50 - 100,0,0,0,0,0,0,1,2,2,0,0,0,0.0,0.0,2.0,0.0
115,F2,500 - 550,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0
116,F2,550 - 600,0,0,0,0,0,0,0,1,1,0,0,0,0.0,0.0,1.0,0.0
117,F2,600 - 650,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0
118,Serpinh1,0 - 50,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0
119,Serpinh1,100 - 150,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0
120,Serpinh1,150 - 200,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0
121,Serpinh1,200 - 250,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0
122,Serpinh1,250 - 300,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0
123,Serpinh1,300 - 350,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0
124,Serpinh1,350 - 400,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0
125,Serpinh1,400 - 450,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0
126,Serpinh1,50 - 100,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0
127,Spp1,0 - 50,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0
128,Spp1,100 - 150,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0
129,Spp1,150 - 200,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0
130,Spp1,200 - 250,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0
131,Spp1,250 - 300,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0
132,Spp1,300 - 350,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0
133,Spp1,50 - 100,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0

In [21]:
fjgids = ['FZ1_F (ms-status_RAT1)', 'FZ2_F (ms-status_RAT2)', 'FZ3_F (ms-status_RAT3)']
mjgids = ['FZ4_M (ms-status_RAT4)', 'FZ5_M (ms-status_RAT5)', 'FZ6_M (ms-status_RAT6)']

fagids = ['JA2_F (ms-status_RAT8)', 'JA5_F (ms-status_RAT11)', 'JA6_F (ms-status_RAT12)']
magids = ['JA1_M (ms-status_RAT7)', 'JA3_M (ms-status_RAT9)', 'JA4_M (ms-status_RAT10)']

In [22]:
maleptms = df[(df['sample'] == 'FZ4_M (ms-status_RAT4)') | (df['sample'] == 'FZ5_M (ms-status_RAT5)') | (df['sample'] == 'FZ6_M (ms-status_RAT6)') | (df['sample'] == 'JA1_M (ms-status_RAT7)') | (df['sample'] == 'JA3_M (ms-status_RAT9)') | (df['sample'] == 'JA4_M (ms-status_RAT10)')]
femaleptms = df[(df['sample'] == 'FZ1_F (ms-status_RAT1)') | (df['sample'] == 'FZ2_F (ms-status_RAT2)') | (df['sample'] == 'FZ3_F (ms-status_RAT3)') |(df['sample'] == 'JA2_F (ms-status_RAT8)') | (df['sample'] == 'JA5_F (ms-status_RAT11)') | (df['sample'] == 'JA6_F (ms-status_RAT12)')]

In [23]:
maleptms = findtotalptms([maleptms], proteinList)
femaleptms = findtotalptms([femaleptms], proteinList)

ldslabels ['FZ4_M (ms-status_RAT4)' 'FZ5_M (ms-status_RAT5)'
 'FZ6_M (ms-status_RAT6)' 'JA1_M (ms-status_RAT7)'
 'JA3_M (ms-status_RAT9)' 'JA4_M (ms-status_RAT10)']

C:\Users\jtudo\AppData\Local\Temp\ipykernel_23936\3987044331.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ds["pep_mods"] = ds["pep_mods"].fillna("")
C:\Users\jtudo\AppData\Local\Temp\ipykernel_23936\3987044331.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ds["pep_mods"] = ds["pep_mods"].astype(str)

ldslabels ['FZ1_F (ms-status_RAT1)' 'FZ2_F (ms-status_RAT2)'
 'FZ3_F (ms-status_RAT3)' 'JA2_F (ms-status_RAT8)'
 'JA5_F (ms-status_RAT11)' 'JA6_F (ms-status_RAT12)']

C:\Users\jtudo\AppData\Local\Temp\ipykernel_23936\3987044331.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ds["pep_mods"] = ds["pep_mods"].fillna("")
C:\Users\jtudo\AppData\Local\Temp\ipykernel_23936\3987044331.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ds["pep_mods"] = ds["pep_mods"].astype(str)

In [24]:
pivmaleptms = pivotmods(maleptms)
pivfemaleptms = pivotmods(femaleptms)

In [25]:
# Testing Normalisation

In [26]:
df_female = pd.read_csv('../data/PLF_Buckley_Female_YFZvsOJA.tsv', sep='\t')
df_male = pd.read_csv('../data/PLF_Buckley_Male_YFZvsOJA.tsv', sep='\t')

In [29]:
# prot = df[df['Uniprot_ID'] == 'CO1A1_RAT']
# prot[prot['Uniprot_ID'] == 'CO1A1_RAT']

In [33]:
def retrieveScaleFactors(dataset, agegroup):
    data = dataset.filter(like=agegroup)
    
    mediantotalcount = data.filter(like="Original").sum(axis=0).median()
    #all_values = data.filter(like="Original").values  # array of all segment counts
    #max_count = all_values.max()
    #min_count = all_values.min()
    
    # print("Max count:", max_count)
    # print("Min count:", min_count)
    # mediantotalcount = statistics.median([min_count, max_count])
    # print(mediantotalcount)
    
    sumtotal = data.filter(like="Original").sum(axis=0)
    # print(sumtotal)
    
    ScalingFactors = mediantotalcount / sumtotal
    # print(type(ScalingFactors), ScalingFactors)
    
    
    cols_to_normalize = data.filter(like="Original").columns

    factors = {}
    
    # Apply scaling factors column by column
    for i, col in enumerate(cols_to_normalize):
        key = f'{col}_NORM'
        val = ScalingFactors[col]
        factors[key] = val 
        # print(i, col, ScalingFactors[col])
        # data[f'{col}_median'] = data[col] * ScalingFactors[col]
        #data[f'{col}_median'] = np.floor(data[f'{col}_median'] + 0.5).astype(int)
    #Old
    return factors

In [34]:
femaleNFs = {}
for p in ['APOE_RAT', 'CO1A1_RAT', 'CO1A2_RAT', 'CO2A1_RAT', 'COMP_RAT', 'OSTP_RAT', 'THRB_RAT']:
    if p in df_female['Uniprot_ID'].unique():
        data = df_female[df_female['Uniprot_ID']== p]
        key = f'{p}_FZ'
        femaleNFs[key] = FuzzyFemaleSF = retrieveScaleFactors(data, 'FZ')
        key = f'{p}_JA'
        femaleNFs[key] = JumboFemaleSF = retrieveScaleFactors(data, 'JA')

In [36]:
maleNFs = {}
for p in ['APOE_RAT', 'CO1A1_RAT', 'CO1A2_RAT', 'CO2A1_RAT', 'COMP_RAT', 'OSTP_RAT', 'THRB_RAT']:
    if p in df_male['Uniprot_ID'].unique():
        data = df_male[df_male['Uniprot_ID']== p]
        key = f'{p}_FZ'
        maleNFs[key] = FuzzyMaleSF = retrieveScaleFactors(data, 'FZ')
        key = f'{p}_JA'
        maleNFs[key] = JumboMaleSF = retrieveScaleFactors(data, 'JA')

In [38]:
import re
malescalingfactorsdf = pivmaleptms.copy()

for key, value in maleNFs.items():
    protein = key.split('_')[0]
    if protein == 'OSTP':
        protein = 'Spp1'
    elif protein == 'CO1A1':
        protein = 'Col1a1'
    elif protein == 'CO1A2':
        protein = 'Col1a2'
    elif protein == 'CO2A1':
        protein = 'Col2a1'
    elif protein == 'THRB':
        protien = 'F2'
    else:
        protein = protein
    for Key, Value in value.items():
        print(f'key: {Key}', f'value: {Value}')

        pattern = r'(FZ\d+|JA\d+)'
        
        match = re.search(pattern, str(Key))
        if match:
            code = match.group(0)
            print(f"Extracted code: {code}")

        mask_rows = malescalingfactorsdf['Prot'].str.contains(protein, case=False)

        # Columns whose name contains 'math'
        mask_cols = [col for col in malescalingfactorsdf.columns if code in col]

        print(f'updating criteria {protein} {code}')
        
        # Update those cells,
        malescalingfactorsdf.loc[mask_rows, mask_cols] = float(Value)

key: Original_FZ4_M (ms-status_RAT4)_NORM value: 1.0
Extracted code: FZ4
updating criteria APOE FZ4
key: Original_FZ5_M (ms-status_RAT5)_NORM value: 1.2105263157894737
Extracted code: FZ5
updating criteria APOE FZ5
key: Original_FZ6_M (ms-status_RAT6)_NORM value: 1.0
Extracted code: FZ6
updating criteria APOE FZ6
key: Original_JA1_M (ms-status_RAT7)_NORM value: 1.0
Extracted code: JA1
updating criteria APOE JA1
key: Original_JA3_M (ms-status_RAT9)_NORM value: 1.2413793103448276
Extracted code: JA3
updating criteria APOE JA3
key: Original_JA4_M (ms-status_RAT10)_NORM value: 0.972972972972973
Extracted code: JA4
updating criteria APOE JA4
key: Original_FZ4_M (ms-status_RAT4)_NORM value: 1.0
Extracted code: FZ4
updating criteria Col1a2 FZ4
key: Original_FZ5_M (ms-status_RAT5)_NORM value: 1.19375
Extracted code: FZ5
updating criteria Col1a2 FZ5
key: Original_FZ6_M (ms-status_RAT6)_NORM value: 0.9408866995073891
Extracted code: FZ6
updating criteria Col1a2 FZ6
key: Original_JA1_M (ms-status_RAT7)_NORM value: 1.202290076335878
Extracted code: JA1
updating criteria Col1a2 JA1
key: Original_JA3_M (ms-status_RAT9)_NORM value: 0.9292035398230089
Extracted code: JA3
updating criteria Col1a2 JA3
key: Original_JA4_M (ms-status_RAT10)_NORM value: 1.0
Extracted code: JA4
updating criteria Col1a2 JA4
key: Original_FZ4_M (ms-status_RAT4)_NORM value: 1.0
Extracted code: FZ4
updating criteria Col2a1 FZ4
key: Original_FZ5_M (ms-status_RAT5)_NORM value: 1.5638297872340425
Extracted code: FZ5
updating criteria Col2a1 FZ5
key: Original_FZ6_M (ms-status_RAT6)_NORM value: 0.8258426966292135
Extracted code: FZ6
updating criteria Col2a1 FZ6
key: Original_JA1_M (ms-status_RAT7)_NORM value: 1.063157894736842
Extracted code: JA1
updating criteria Col2a1 JA1
key: Original_JA3_M (ms-status_RAT9)_NORM value: 1.0
Extracted code: JA3
updating criteria Col2a1 JA3
key: Original_JA4_M (ms-status_RAT10)_NORM value: 0.8938053097345132
Extracted code: JA4
updating criteria Col2a1 JA4
key: Original_FZ4_M (ms-status_RAT4)_NORM value: 1.0
Extracted code: FZ4
updating criteria COMP FZ4
key: Original_FZ5_M (ms-status_RAT5)_NORM value: 4.0
Extracted code: FZ5
updating criteria COMP FZ5
key: Original_FZ6_M (ms-status_RAT6)_NORM value: 0.8
Extracted code: FZ6
updating criteria COMP FZ6
key: Original_JA1_M (ms-status_RAT7)_NORM value: 1.0
Extracted code: JA1
updating criteria COMP JA1
key: Original_JA3_M (ms-status_RAT9)_NORM value: 0.5
Extracted code: JA3
updating criteria COMP JA3
key: Original_JA4_M (ms-status_RAT10)_NORM value: 1.2
Extracted code: JA4
updating criteria COMP JA4
key: Original_FZ4_M (ms-status_RAT4)_NORM value: 1.0
Extracted code: FZ4
updating criteria Spp1 FZ4
key: Original_FZ5_M (ms-status_RAT5)_NORM value: 3.8333333333333335
Extracted code: FZ5
updating criteria Spp1 FZ5
key: Original_FZ6_M (ms-status_RAT6)_NORM value: 0.7540983606557377
Extracted code: FZ6
updating criteria Spp1 FZ6
key: Original_JA1_M (ms-status_RAT7)_NORM value: 1.0
Extracted code: JA1
updating criteria Spp1 JA1
key: Original_JA3_M (ms-status_RAT9)_NORM value: 2.0
Extracted code: JA3
updating criteria Spp1 JA3
key: Original_JA4_M (ms-status_RAT10)_NORM value: 0.6666666666666666
Extracted code: JA4
updating criteria Spp1 JA4

In [40]:
femalescalingfactorsdf = pivfemaleptms.copy()

for key, value in femaleNFs.items():
    protein = key.split('_')[0]
    if protein == 'OSTP':
        protein = 'Spp1'
    elif protein == 'CO1A1':
        protein = 'Col1a1'
    elif protein == 'CO1A2':
        protein = 'Col1a2'
    elif protein == 'CO2A1':
        protein = 'Col2a1'
    elif protein == 'THRB':
        protien = 'F2'
    else:
        protein = protein
    for Key, Value in value.items():
        print(f'key: {Key}', f'value: {Value}')

        pattern = r'(FZ\d+|JA\d+)'
        
        match = re.search(pattern, str(Key))
        if match:
            code = match.group(0)
            print(f"Extracted code: {code}")

        mask_rows = femalescalingfactorsdf['Prot'].str.contains(protein, case=False)

        # Columns whose name contains 'math'
        mask_cols = [col for col in femalescalingfactorsdf.columns if code in col]

        print(f'updating criteria {protein} {code}')
        
        # Update those cells,
        femalescalingfactorsdf.loc[mask_rows, mask_cols] = float(Value)

key: Original_FZ1_F (ms-status_RAT1)_NORM value: 1.0769230769230769
Extracted code: FZ1
updating criteria APOE FZ1
key: Original_FZ2_F (ms-status_RAT2)_NORM value: 0.45161290322580644
Extracted code: FZ2
updating criteria APOE FZ2
key: Original_FZ3_F (ms-status_RAT3)_NORM value: 1.0
Extracted code: FZ3
updating criteria APOE FZ3
key: Original_JA2_F (ms-status_RAT8)_NORM value: 1.0344827586206897
Extracted code: JA2
updating criteria APOE JA2
key: Original_JA5_F (ms-status_RAT11)_NORM value: 0.8108108108108109
Extracted code: JA5
updating criteria APOE JA5
key: Original_JA6_F (ms-status_RAT12)_NORM value: 1.0
Extracted code: JA6
updating criteria APOE JA6
key: Original_FZ1_F (ms-status_RAT1)_NORM value: 1.008298755186722
Extracted code: FZ1
updating criteria Col1a1 FZ1
key: Original_FZ2_F (ms-status_RAT2)_NORM value: 0.9310344827586207
Extracted code: FZ2
updating criteria Col1a1 FZ2
key: Original_FZ3_F (ms-status_RAT3)_NORM value: 1.0
Extracted code: FZ3
updating criteria Col1a1 FZ3
key: Original_JA2_F (ms-status_RAT8)_NORM value: 1.0
Extracted code: JA2
updating criteria Col1a1 JA2
key: Original_JA5_F (ms-status_RAT11)_NORM value: 1.1511879049676026
Extracted code: JA5
updating criteria Col1a1 JA5
key: Original_JA6_F (ms-status_RAT12)_NORM value: 0.8433544303797469
Extracted code: JA6
updating criteria Col1a1 JA6
key: Original_FZ1_F (ms-status_RAT1)_NORM value: 1.0
Extracted code: FZ1
updating criteria Col1a2 FZ1
key: Original_FZ2_F (ms-status_RAT2)_NORM value: 0.7624521072796935
Extracted code: FZ2
updating criteria Col1a2 FZ2
key: Original_FZ3_F (ms-status_RAT3)_NORM value: 1.0257731958762886
Extracted code: FZ3
updating criteria Col1a2 FZ3
key: Original_JA2_F (ms-status_RAT8)_NORM value: 1.0
Extracted code: JA2
updating criteria Col1a2 JA2
key: Original_JA5_F (ms-status_RAT11)_NORM value: 1.0761904761904761
Extracted code: JA5
updating criteria Col1a2 JA5
key: Original_JA6_F (ms-status_RAT12)_NORM value: 0.8248175182481752
Extracted code: JA6
updating criteria Col1a2 JA6
key: Original_FZ1_F (ms-status_RAT1)_NORM value: 1.0
Extracted code: FZ1
updating criteria Col2a1 FZ1
key: Original_FZ2_F (ms-status_RAT2)_NORM value: 0.7760416666666666
Extracted code: FZ2
updating criteria Col2a1 FZ2
key: Original_FZ3_F (ms-status_RAT3)_NORM value: 1.2314049586776858
Extracted code: FZ3
updating criteria Col2a1 FZ3
key: Original_JA2_F (ms-status_RAT8)_NORM value: 1.118811881188119
Extracted code: JA2
updating criteria Col2a1 JA2
key: Original_JA5_F (ms-status_RAT11)_NORM value: 1.0
Extracted code: JA5
updating criteria Col2a1 JA5
key: Original_JA6_F (ms-status_RAT12)_NORM value: 0.9912280701754386
Extracted code: JA6
updating criteria Col2a1 JA6
key: Original_FZ1_F (ms-status_RAT1)_NORM value: 1.0
Extracted code: FZ1
updating criteria COMP FZ1
key: Original_FZ2_F (ms-status_RAT2)_NORM value: 0.7777777777777778
Extracted code: FZ2
updating criteria COMP FZ2
key: Original_FZ3_F (ms-status_RAT3)_NORM value: 2.3333333333333335
Extracted code: FZ3
updating criteria COMP FZ3
key: Original_JA2_F (ms-status_RAT8)_NORM value: 0.6666666666666666
Extracted code: JA2
updating criteria COMP JA2
key: Original_JA5_F (ms-status_RAT11)_NORM value: 1.6
Extracted code: JA5
updating criteria COMP JA5
key: Original_JA6_F (ms-status_RAT12)_NORM value: 1.0
Extracted code: JA6
updating criteria COMP JA6
key: Original_FZ1_F (ms-status_RAT1)_NORM value: 1.75
Extracted code: FZ1
updating criteria Spp1 FZ1
key: Original_FZ2_F (ms-status_RAT2)_NORM value: 0.7291666666666666
Extracted code: FZ2
updating criteria Spp1 FZ2
key: Original_FZ3_F (ms-status_RAT3)_NORM value: 1.0
Extracted code: FZ3
updating criteria Spp1 FZ3
key: Original_JA2_F (ms-status_RAT8)_NORM value: 3.0
Extracted code: JA2
updating criteria Spp1 JA2
key: Original_JA5_F (ms-status_RAT11)_NORM value: 1.0
Extracted code: JA5
updating criteria Spp1 JA5
key: Original_JA6_F (ms-status_RAT12)_NORM value: 1.0
Extracted code: JA6
updating criteria Spp1 JA6
key: Original_FZ1_F (ms-status_RAT1)_NORM value: 1.6363636363636365
Extracted code: FZ1
updating criteria THRB FZ1
key: Original_FZ2_F (ms-status_RAT2)_NORM value: 1.0
Extracted code: FZ2
updating criteria THRB FZ2
key: Original_FZ3_F (ms-status_RAT3)_NORM value: 0.9
Extracted code: FZ3
updating criteria THRB FZ3
key: Original_JA2_F (ms-status_RAT8)_NORM value: 0.9512195121951219
Extracted code: JA2
updating criteria THRB JA2
key: Original_JA5_F (ms-status_RAT11)_NORM value: 1.0
Extracted code: JA5
updating criteria THRB JA5
key: Original_JA6_F (ms-status_RAT12)_NORM value: 1.1470588235294117
Extracted code: JA6
updating criteria THRB JA6

In [42]:
normalisedmaledf = pivmaleptms.copy()
normalisedfemaledf = pivfemaleptms.copy()

malenum_cols = normalisedmaledf.select_dtypes(include='float').columns
femalenum_cols = normalisedfemaledf.select_dtypes(include='float').columns

normalisedmaledf[malenum_cols] = np.round(normalisedmaledf[malenum_cols] * malescalingfactorsdf[malenum_cols])
normalisedfemaledf[femalenum_cols] = np.round(normalisedfemaledf[femalenum_cols] * femalescalingfactorsdf[femalenum_cols])

In [44]:
RegionsToSearch = {
    "col1a1": [
        (950, 1000),
        (1000, 1050)
    ],
    "col1a2": [
        (1000, 1050),
        (1050, 1100)
    ],
    "col2a1": [
        (550, 600),
        (600, 650),
        (800, 850),
        (850, 900),
        (1150, 1200),
        (1200, 1250),
        (1300, 1350),
        (1350, 1400)
    ],
    "spp1": [
        (0, 50),
        (150, 200)
    ],
    "F2": [
        (350, 400)
    ],
    "APOE": [
        (200, 250),
        (250, 300)
    ],
    "Comp": [
        (600, 650)
    ]
}

In [49]:
teststring = '400 - 450'
teststring.split()

['400', '-', '450']

In [47]:
import matplotlib.pyplot as plt
from scipy.stats import mannwhitneyu

# Example: load your dataframe
# df = pd.read_csv("your_data.csv")  
def performPTMAnalysis:

    # Define RegionsToSearch
    RegionsToSearch = {
        "col1a1": [(950, 1000), (1000, 1050)],
        "col1a2": [(1000, 1050), (1050, 1100)],
        "col2a1": [(550, 600), (600, 650), (800, 850), (850, 900), (1150, 1200), (1200, 1250), (1300, 1350), (1350, 1400)],
        "spp1": [(0, 50), (150, 200)],
        "F2": [(350, 400)],
        "APOE": [(200, 250), (250, 300)],
        "Comp": [(600, 650)]
    }

    # Modifications and corresponding columns
    mods = ["dNQ", "oxK", "oxP", "oxM"]

    # Function to parse string range like "950-1000" to tuple (950, 1000)
    for key, value in RegionsToSearch:
        protein = key
        regions = value

        for r in regions:
            low = r[0]
            high = r[1]
            
            for mod in mods:
                relcols = data.columns.contains(mod)
                
                data = d[(d['Prot'] == protein) and (d['50aa_reg_range'].split()[0] == low) and (d['50aa_reg_range'].split()[1] == high)]